<?php // this is an autogenerated file - do not edit (created 2010-03-10 17:37:02)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'sgl2_bootstrap_abstract' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Bootstrap/Abstract.php',
         'sgl2_bootstrap' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Bootstrap.php',
         'sgl2_command_abstract' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Command/Abstract.php',
         'sgl2_context_app' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Context/App.php',
         'sgl2_context' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Context.php',
         'sgl2_controller_app' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Controller/App.php',
         'sgl2_controller_front' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Controller/Front.php',
         'sgl2_exception' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Exception.php',
         'sgl2_renderer_html_flexystrategy' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Renderer/Html/FlexyStrategy.php',
         'sgl2_renderer_outputstrategy' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Renderer/OutputStrategy.php',
         'sgl2_renderer_text' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Renderer/Text.php',
         'sgl2_request' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Request.php',
         'sgl2_response' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Response.php',
         'sgl2_router' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/Router.php',
         'sgl2_view_abstract' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/View/Abstract.php',
         'sgl2_view_html' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/View/Html.php',
         'sgl2_view_text' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/SGL2/View/Text.php',
         'uber_component_exception' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Component/Exception.php',
         'uber_event_dispatcher' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Event/Dispatcher.php',
         'uber_event_interface' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Event/Interface.php',
         'uber_event_listener_collection' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Event/Listener/Collection.php',
         'uber_event_listener_interface' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Event/Listener/Interface.php',
         'uber_event' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Event.php',
         'uber_exception' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Exception.php',
         'uber_lazy_mixin_exception' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Lazy/Mixin/Exception.php',
         'uber_lazy_mixin' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Lazy/Mixin.php',
         'uber_lazy' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Lazy.php',
         'uber_loader_exception' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Loader/Exception.php',
         'uber_loader' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Loader.php',
         'uber_object_exception' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Object/Exception.php',
         'uber_object' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber/Object.php',
         'uber' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Uber.php',
         'zend_config_exception' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config/Exception.php',
         'zend_config_ini' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config/Ini.php',
         'zend_config_writer_array' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config/Writer/Array.php',
         'zend_config_writer_fileabstract' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config/Writer/FileAbstract.php',
         'zend_config_writer_ini' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config/Writer/Ini.php',
         'zend_config_writer_xml' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config/Writer/Xml.php',
         'zend_config_writer' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config/Writer.php',
         'zend_config_xml' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config/Xml.php',
         'zend_config' => '/Users/demian/Sites/seagull/sketch/sgl2/src/lib/Zend/Config.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . "/" . $classes[$cn];
      }
   }
);
?>
