<?php
$conf['site']['name'] = "Seagull Framework";
$conf['site']['description'] = "Coming soon to a webserver near you.";
$conf['site']['keywords'] = "seagull, php, framework, cms, content management";
$conf['site']['compression'] = "";
$conf['site']['outputBuffering'] = "";
$conf['site']['frontScriptName'] = "index.php";
$conf['site']['defaultModule'] = "default";
$conf['site']['defaultController'] = "default";
$conf['site']['defaultParams'] = "";
$conf['site']['templateEngine'] = "flexy";
$conf['site']['extendedLocale'] = "";
$conf['site']['localeCategory'] = "\'LC_ALL\'";
$conf['site']['defaultTheme'] = "default";
$conf['site']['layout'] = "layout.html";
$conf['site']['filterChain'] = "";
$conf['site']['rolesHaveAdminGui'] = "\'SGL2_ADMIN\'";
$conf['site']['serverTimeOffset'] = "UTC";
$conf['site']['baseUrl'] = "http://localhost/seagull/trunk/www";
$conf['cookie']['path'] = "/";
$conf['cookie']['domain'] = "";
$conf['cookie']['secure'] = "";
$conf['cookie']['name'] = "SGLSESSID";
$conf['cookie']['rememberMeEnabled'] = "";
$conf['session']['maxLifetime'] = "0";
$conf['session']['handler'] = "file";
$conf['session']['allowedInUri'] = "1";
$conf['session']['savePath'] = "";
$conf['debug']['authorisationEnabled'] = "1";
$conf['debug']['emailAdminThreshold'] = "\'PEAR_LOG_EMERG\'";
$conf['translation']['fallbackLang'] = "en_utf_8";
$conf['p3p']['policies'] = "1";
$conf['p3p']['policyLocation'] = "";
$conf['p3p']['compactPolicy'] = "CUR ADM OUR NOR STA NID";
$conf['tuples']['version'] = "2.0.0";
return $conf;
?>